/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';
import Button1 from 'components/Button1/Button1';

 
const Card1 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  boxShadow: `0px 4px 6px rgba(3, 0, 161, 0.2)`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  height: `500px`,  
  width: "100%",  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Image = styled("div")({  
  backgroundImage: `url(assets/images/Card_Image.png)`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `257px`,  
  margin: `0px`,  
  overflow: `hidden`,  
});
  
const TextButton = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-end`,  
  alignItems: `flex-end`,  
  padding: `0px 40px`,  
  boxSizing: `border-box`,  
  margin: `30px 0px 0px 0px`,  
});
  
const LoremIpsumTestToBeSe = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `400`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  width: `297.86px`,  
  zIndex: `2`,  
  margin: `0px`,  
});
  
const ButtonClicked = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(107, 104, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  height: `48px`,  
  width: `138px`,  
  zIndex: `1`,  
  margin: `30px 0px 0px 0px`,  
});
  
const Button2 = styled(Button1)(({ theme }) =>({  
  zIndex: `0`,  
  margin: `30px 0px 0px 0px`,  
}));
 
function Card(props) {
  return (
    <Card1 className={props.className} >
      <Image >
      </Image>
      <TextButton >
        <LoremIpsumTestToBeSe >
          {`Lorem ipsum test to be seen and not read for placement only. Lorem ipsum test to be seen.`}
            </LoremIpsumTestToBeSe>
        <ButtonClicked >
          {`Button Clicked!`}
            </ButtonClicked>
        <Button2   />
      </TextButton>
    </Card1>
  );
}

export default Card;
