/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { Button, Link } from '@mui/material';
import ActionsIconImage from 'src/assets/images/Web3_Actions_Icon_6.png';
import DashboardImage from 'src/assets/images/Web3_dashboard.png';
import Icon1Image from 'src/assets/images/Web3_icon_5.png';
import Icon2Image from 'src/assets/images/Web3_icon_4.png';
import Icon3Image from 'src/assets/images/Web3_icon_3.png';
import ActionsIcon1Image from 'src/assets/images/Web3_Actions_Icon_5.png';
import FigmaToReactWithMuiImage from 'src/assets/images/Web3_Figma_to_React_with_MUI.png';
import Icon4Image from 'src/assets/images/Web3_icon_2.png';
import Icon5Image from 'src/assets/images/Web3_icon_1.png';
import Icon6Image from 'src/assets/images/Web3_icon.png';
import ActionsIcon2Image from 'src/assets/images/Web3_Actions_Icon_4.png';
import ActionsIcon3Image from 'src/assets/images/Web3_Actions_Icon_3.png';
import Chart1Image from 'src/assets/images/Web3_chart_1_1.png';
import ActionsIcon4Image from 'src/assets/images/Web3_Actions_Icon_2.png';
import ActionsIcon5Image from 'src/assets/images/Web3_Actions_Icon_1.png';
import ActionsIcon6Image from 'src/assets/images/Web3_Actions_Icon.png';
import { styled } from '@mui/material/styles';
import HeroDesktopImage from 'src/assets/images/Web3_hero_desktop.png';
import Sec2Image from 'src/assets/images/Web3_sec2.png';
import Sec3Image from 'src/assets/images/Web3_sec3.png';
import Rectangle178Image from 'src/assets/images/Web3_Rectangle_178_2.png';
import Rectangle1781Image from 'src/assets/images/Web3_Rectangle_178_1.png';
import Rectangle1782Image from 'src/assets/images/Web3_Rectangle_178.png';
import Sec7Image from 'src/assets/images/Web3_sec7.png';
import Chart11Image from 'src/assets/images/Web3_chart_1.png';
import DiscoverSecImage from 'src/assets/images/Web3_Discover_Sec.png';
import Sec4ImageImage from 'src/assets/images/Web3_sec4_Image.png';
import { Web3Props } from 'src/types';

 
const ScreensDesktop: any = styled("div")({  
  backgroundColor: `rgba(23, 23, 23, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  width: `1440px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const HeroBg: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  overflow: `hidden`,  
});
  
const HeroContent: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `40px 0px 0px 0px`,  
  boxSizing: `border-box`,  
  width: `1440px`,  
  margin: `0px`,  
});
  
const HeroDesktop: any = styled("div")({  
  backgroundImage: `url(${HeroDesktopImage})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `80px 180px 60px 110px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  overflow: `hidden`,  
});
  
const HeroAll: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const HeroContent1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 140px 0px 0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Frame125: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `110px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `80px`,  
  textTransform: `none`,  
  background: `linear-gradient(-90deg, rgba(254, 136, 136, 1) 27.16229514331244%, rgba(128, 102, 255, 1) 97.86200295926109%)`,  
  backgroundClip: `text`,  
  WebkitBackgroundClip: `text`,  
  WebkitTextFillColor: `transparent`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `110px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `92px`,  
  textTransform: `none`,  
  width: `721px`,  
  margin: `8px 0px 0px 0px`,  
});
  
const HeroSub: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `23px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `24px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `34px`,  
  textTransform: `none`,  
  width: `614px`,  
  margin: `0px`,  
});
  
const ButtonOutlined: any = styled(Button)({  
  width: `180px`,  
  margin: `0px 0px 0px 10px`,  
});
  
const Sec1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 180px 40px 180px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `30px 0px 0px 0px`,  
});
  
const Frame1251: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1080px`,  
  margin: `0px`,  
});
  
const Sec4Text: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Subtitle: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon: any = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  margin: `0px`,  
});
  
const NewWay: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  width: `417px`,  
  margin: `0px 0px 0px 8px`,  
});
  
const Frame1252: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `18px 0px 0px 0px`,  
});
  
const Achieve: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  width: `442px`,  
  margin: `0px`,  
});
  
const Product: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  background: `linear-gradient(-90deg, rgba(254, 136, 136, 1) 27.16229514331244%, rgba(128, 102, 255, 1) 97.86200295926109%)`,  
  backgroundClip: `text`,  
  WebkitBackgroundClip: `text`,  
  WebkitTextFillColor: `transparent`,  
  margin: `0px`,  
});
  
const DevelopmentNirvana: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  width: `442px`,  
  margin: `0px`,  
});
  
const Dashboard: any = styled("img")({  
  height: `340px`,  
  width: `608px`,  
  objectFit: `cover`,  
  margin: `0px 0px 0px 30px`,  
});
  
const Divider: any = styled("div")({  
  backgroundColor: `rgba(46, 46, 46, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `40px 0px 0px 0px`,  
});
  
const BuildBoldPoints: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1080px`,  
  margin: `40px 0px 0px 0px`,  
});
  
const Frame1253: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `302.67px`,  
});
  
const Icon1: any = styled("img")({  
  height: `30px`,  
  width: `30px`,  
  margin: `0px`,  
});
  
const MakeExisting: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `800`,  
  fontSize: `24px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  width: `303px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const MakeExisting1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  width: `303px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const Frame1254: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `302.67px`,  
});
  
const Icon2: any = styled("img")({  
  height: `30px`,  
  width: `30px`,  
  margin: `0px`,  
});
  
const BuildConsistently: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `800`,  
  fontSize: `24px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `12px 0px 0px 0px`,  
});
  
const BuildConsistently1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `12px 0px 0px 0px`,  
});
  
const Frame1255: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `302.67px`,  
});
  
const Icon3: any = styled("img")({  
  height: `30px`,  
  width: `30px`,  
  margin: `0px`,  
});
  
const IterateBetween: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `800`,  
  fontSize: `24px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `12px 0px 0px 0px`,  
});
  
const IterateBetween1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `12px 0px 0px 0px`,  
});
  
const Sec2: any = styled("div")({  
  backgroundImage: `url(${Sec2Image})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `80px 180px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `30px 0px 0px 0px`,  
});
  
const Frame1256: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1080px`,  
  margin: `0px`,  
});
  
const Sec4Text1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Subtitle1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon1: any = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  margin: `0px`,  
});
  
const NewWay1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  width: `417px`,  
  margin: `0px 0px 0px 8px`,  
});
  
const Frame1257: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `24px 0px 0px 0px`,  
});
  
const Frame1258: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `442px`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  background: `linear-gradient(-90deg, rgba(254, 136, 136, 1) 27.16229514331245%, rgba(128, 102, 255, 1) 97.8620029592611%)`,  
  backgroundClip: `text`,  
  WebkitBackgroundClip: `text`,  
  WebkitTextFillColor: `transparent`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  width: `442px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `500`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `24px 0px 0px 0px`,  
});
  
const FigmaToReactWithMui: any = styled("img")({  
  height: `444px`,  
  width: `497.07px`,  
  margin: `0px 0px 0px 30px`,  
});
  
const Divider1: any = styled("div")({  
  backgroundColor: `rgba(46, 46, 46, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const BuildBoldPoints1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `30px 0px 0px 0px`,  
  boxSizing: `border-box`,  
  width: `1080px`,  
  margin: `0px`,  
});
  
const Frame1259: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Icon4: any = styled("img")({  
  height: `30px`,  
  width: `30px`,  
  margin: `0px`,  
});
  
const MakeExisting2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `800`,  
  fontSize: `24px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  width: `302.67px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const MakeExisting3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  width: `302.67px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const Frame12510: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Icon5: any = styled("img")({  
  height: `30px`,  
  width: `30px`,  
  margin: `0px`,  
});
  
const BuildConsistently2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `800`,  
  fontSize: `24px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  width: `302.67px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const BuildConsistently3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  width: `302.67px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const Frame126: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Icon6: any = styled("img")({  
  height: `30px`,  
  width: `30px`,  
  margin: `0px`,  
});
  
const IterateBetween2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `800`,  
  fontSize: `24px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  width: `302.67px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const IterateBetween3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  width: `302.67px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const Sec3: any = styled("div")({  
  backgroundImage: `url(${Sec3Image})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 180px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `30px 0px 0px 0px`,  
});
  
const Frame127: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1080px`,  
  margin: `0px`,  
});
  
const Subtitle2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon2: any = styled("img")({  
  height: `14px`,  
  width: `12.95px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  width: `385.7px`,  
  margin: `0px 0px 0px 6px`,  
});
  
const DiscoverThe: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `36px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `34px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `24px 0px 0px 0px`,  
});
  
const Examples: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `24px 0px 0px 0px`,  
});
  
const Frame12511: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `353.33px`,  
});
  
const Rectangle178: any = styled("div")({  
  backgroundImage: `url(${Rectangle178Image})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  border: `1px solid rgba(255, 255, 255, 0.35)`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `233px`,  
  margin: `0px`,  
});
  
const ImportYourDifferen: any = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `24px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `14px 0px 0px 0px`,  
});
  
const Frame1261: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `353.33px`,  
});
  
const Rectangle1781: any = styled("div")({  
  backgroundImage: `url(${Rectangle1781Image})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  border: `1px solid rgba(255, 255, 255, 0.35)`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `233px`,  
  margin: `0px`,  
});
  
const ImportYourDifferen1: any = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `24px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `14px 0px 0px 0px`,  
});
  
const Frame1271: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `353.33px`,  
});
  
const Rectangle1782: any = styled("div")({  
  backgroundImage: `url(${Rectangle1782Image})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  border: `1px solid rgba(255, 255, 255, 0.35)`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `233px`,  
  margin: `0px`,  
});
  
const ImportYourDifferen2: any = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `24px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `14px 0px 0px 0px`,  
});
  
const Sec6: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `90px 180px 0px 180px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `30px 0px 0px 0px`,  
});
  
const Frame171: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Frame1272: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 100px 0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Subtitle3: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon3: any = styled("img")({  
  height: `14px`,  
  width: `12.95px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  width: `385.7px`,  
  margin: `0px 0px 0px 6px`,  
});
  
const DiscoverThe1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `36px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `34px`,  
  textTransform: `none`,  
  width: `777px`,  
  margin: `24px 0px 0px 0px`,  
});
  
const Chart1: any = styled("img")({  
  height: `1160px`,  
  width: `986px`,  
  objectFit: `contain`,  
  margin: `24px 0px 0px 0px`,  
});
  
const Sec7: any = styled("div")({  
  backgroundImage: `url(${Sec7Image})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 180px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `30px 0px 0px 0px`,  
});
  
const Frame1711: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Frame1273: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 70px 60px 0px`,  
  boxSizing: `border-box`,  
  width: `1080px`,  
  margin: `0px`,  
});
  
const Subtitle4: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon4: any = styled("img")({  
  height: `14px`,  
  width: `12.95px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm4: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  width: `385.7px`,  
  margin: `0px 0px 0px 6px`,  
});
  
const DiscoverThe2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `36px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `34px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `24px 0px 0px 0px`,  
});
  
const Frame12512: any = styled("div")({  
  border: `3px solid rgba(255, 255, 255, 0.29)`,  
  boxSizing: `border-box`,  
  borderRadius: `30px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px`,  
  height: `331px`,  
  width: `1080px`,  
  margin: `24px 0px 0px 0px`,  
  overflow: `hidden`,  
});
  
const Chart11: any = styled("div")({  
  backgroundImage: `url(${Chart11Image})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  border: `1px solid rgba(0, 0, 0, 1)`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `329px`,  
  margin: `0px`,  
});
  
const LearnMore: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 10px 0px`,  
  boxSizing: `border-box`,  
  margin: `24px 0px 0px 0px`,  
});
  
const Link1: any = styled(Link)({  
  color: `rgba(254, 136, 136, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const About: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 5px`,  
});
  
const ReadyVid: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `70px 210px 70px 250px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `30px 0px 0px 0px`,  
});
  
const Frame1274: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Frame12513: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Subtitle5: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon5: any = styled("img")({  
  height: `14px`,  
  width: `12.95px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm5: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  width: `385.7px`,  
  margin: `0px 0px 0px 6px`,  
});
  
const DiscoverThe3Span1: any = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `64px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `60px`,  
  textTransform: `none`,  
});
  
const DiscoverThe3Span2: any = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(254, 136, 136, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `64px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `60px`,  
  textTransform: `none`,  
});
  
const DiscoverThe3Span3: any = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `64px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `60px`,  
  textTransform: `none`,  
});
  
const DiscoverThe3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `64px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `60px`,  
  textTransform: `none`,  
  width: `980px`,  
  margin: `18px 0px 0px 0px`,  
});
  
const Typeform: any = styled("div")({  
  backgroundColor: `rgba(196, 196, 196, 1)`,  
  height: `610px`,  
  width: `980px`,  
  margin: `18px 0px 0px 0px`,  
});
  
const DiscoverSec: any = styled("div")({  
  backgroundImage: `url(${DiscoverSecImage})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `90px 180px 0px 180px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `30px 0px 0px 0px`,  
});
  
const Frame1275: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 100px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Frame1262: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Subtitle6: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon6: any = styled("img")({  
  height: `14px`,  
  width: `12.95px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm6: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  width: `385.7px`,  
  margin: `0px 0px 0px 6px`,  
});
  
const DiscoverThe4Span1: any = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `64px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
});
  
const DiscoverThe4Span2: any = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(254, 136, 136, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `64px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
});
  
const DiscoverThe4Span3: any = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `64px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
});
  
const DiscoverThe4: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `64px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `24px 0px 0px 0px`,  
});
  
const ImportYourDifferen3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  width: `622.49px`,  
  margin: `24px 0px 0px 0px`,  
});
  
const LearnMore1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `980px`,  
  margin: `24px 0px 0px 0px`,  
});
  
const About1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Link2: any = styled(Link)({  
  color: `rgba(254, 136, 136, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 5px`,  
});
  
const ButtonOutlined1: any = styled(Button)({  
  margin: `24px 0px 0px 0px`,  
});
  
const BtmImage: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `30px 0px 0px 0px`,  
});
  
const Sec4Image: any = styled("div")({  
  backgroundImage: `url(${Sec4ImageImage})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  height: `512px`,  
  width: `1440px`,  
  margin: `0px`,  
});
 
function Web3(props: Web3Props): JSX.Element {
  return (
    <ScreensDesktop className={props.className} >
      <HeroBg >
        <HeroContent >
          <HeroDesktop >
            <HeroAll >
              <HeroContent1 >
                <Frame125 >
                  <TakeDesignToLaunc >
                    {`Frontend`}
                      </TakeDesignToLaunc>
                  <TakeDesignToLaunc1 >
                    {`for your Web3 Apps`}
                      </TakeDesignToLaunc1>
                </Frame125>
                <HeroSub >
                  <NeoFromQuestAiEm >
                    {`Know React.js? Use Figma? You can build Web3 Apps using Quest. No special additional skills needed.`}
                      </NeoFromQuestAiEm>
                  <ButtonOutlined variant="outlined" size="large" color="primary"    > Sign Up Now </ButtonOutlined>
                </HeroSub>
              </HeroContent1>
            </HeroAll>
          </HeroDesktop>
        </HeroContent>
      </HeroBg>
      <Sec1 >
        <Frame1251 >
          <Sec4Text >
            <Subtitle >
              <ActionsIcon  src={ActionsIconImage} alt={"Actions Icon"}/>
              <NewWay >
                {`FRONTEND PERFECTION`}
                  </NewWay>
            </Subtitle>
            <Frame1252 >
              <Achieve >
                {`Grow your  `}
                  </Achieve>
              <Product >
                {`Web3 App`}
                  </Product>
              <DevelopmentNirvana >
                {`with the best user experience`}
                  </DevelopmentNirvana>
            </Frame1252>
          </Sec4Text>
          <Dashboard  src={DashboardImage} alt={"dashboard"}/>
        </Frame1251>
        <Divider >
        </Divider>
        <BuildBoldPoints >
          <Frame1253 >
            <Icon1  src={Icon1Image} alt={"icon"}/>
            <MakeExisting >
              {`Stand out from the crowd`}
                </MakeExisting>
            <MakeExisting1 >
              {`Build a high quality experience that conveys the brand value to your customers`}
                </MakeExisting1>
          </Frame1253>
          <Frame1254 >
            <Icon2  src={Icon2Image} alt={"icon"}/>
            <BuildConsistently >
              {`Build trust`}
                </BuildConsistently>
            <BuildConsistently1 >
              {`A professional, best-in-class user experience builds credibility and increases engagement`}
                </BuildConsistently1>
          </Frame1254>
          <Frame1255 >
            <Icon3  src={Icon3Image} alt={"icon"}/>
            <IterateBetween >
              {`Iterate easily`}
                </IterateBetween>
            <IterateBetween1 >
              {`Experiment, and A/B test as easily as prototyping`}
                </IterateBetween1>
          </Frame1255>
        </BuildBoldPoints>
      </Sec1>
      <Sec2 >
        <Frame1256 >
          <Sec4Text1 >
            <Subtitle1 >
              <ActionsIcon1  src={ActionsIcon1Image} alt={"Actions Icon"}/>
              <NewWay1 >
                {`COMPLIMENT YOUR SKILLs`}
                  </NewWay1>
            </Subtitle1>
            <Frame1257 >
              <Frame1258 >
                <TakeDesignToLaunc2 >
                  {`Build Fast`}
                    </TakeDesignToLaunc2>
              </Frame1258>
              <TakeDesignToLaunc3 >
                {`with the tools & frameworks that you already know and love`}
                  </TakeDesignToLaunc3>
            </Frame1257>
            {false &&
              <NeoFromQuestAiEm1 >
                {`Build as fast as you can design it. Building has never been this easy, detailed and fast.`}
                  </NeoFromQuestAiEm1>
            }
          </Sec4Text1>
          <FigmaToReactWithMui  src={FigmaToReactWithMuiImage} alt={"Figma to React with MUI"}/>
        </Frame1256>
        <Divider1 >
        </Divider1>
        <BuildBoldPoints1 >
          <Frame1259 >
            <Icon4  src={Icon4Image} alt={"icon"}/>
            <MakeExisting2 >
              {`Design tool`}
                </MakeExisting2>
            <MakeExisting3 >
              {`Design in Figma, just like you did for Web2, and Quest figures out your design.`}
                </MakeExisting3>
          </Frame1259>
          <Frame12510 >
            <Icon5  src={Icon5Image} alt={"icon"}/>
            <BuildConsistently2 >
              {`Code format`}
                </BuildConsistently2>
            <BuildConsistently3 >
              {`Export React.js code components that are clean and efficient - just as good as hand coded. Add any custom code and extend it as much as you want.`}
                </BuildConsistently3>
          </Frame12510>
          <Frame126 >
            <Icon6  src={Icon6Image} alt={"icon"}/>
            <IterateBetween2 >
              {`Deploy and launch`}
                </IterateBetween2>
            <IterateBetween3 >
              {`Use your own CI/CD pipeline just like you do today.`}
                </IterateBetween3>
          </Frame126>
        </BuildBoldPoints1>
      </Sec2>
      <Sec3 >
        <Frame127 >
          <Subtitle2 >
            <ActionsIcon2  src={ActionsIcon2Image} alt={"Actions Icon"}/>
            <NeoFromQuestAiEm2 >
              {`THE FUTURE of WEB3`}
                </NeoFromQuestAiEm2>
          </Subtitle2>
          <DiscoverThe >
            {`Build Apps for:`}
              </DiscoverThe>
          <Examples >
            <Frame12511 >
              <Rectangle178 >
              </Rectangle178>
              <ImportYourDifferen >
                {`NFT`}
                  </ImportYourDifferen>
            </Frame12511>
            <Frame1261 >
              <Rectangle1781 >
              </Rectangle1781>
              <ImportYourDifferen1 >
                {`Defi`}
                  </ImportYourDifferen1>
            </Frame1261>
            <Frame1271 >
              <Rectangle1782 >
              </Rectangle1782>
              <ImportYourDifferen2 >
                {`Portfolio 
Management`}
                  </ImportYourDifferen2>
            </Frame1271>
          </Examples>
        </Frame127>
      </Sec3>
      <Sec6 >
        <Frame171 >
          <Frame1272 >
            <Subtitle3 >
              <ActionsIcon3  src={ActionsIcon3Image} alt={"Actions Icon"}/>
              <NeoFromQuestAiEm3 >
                {`FOCUS ON COMPOSABILITY`}
                  </NeoFromQuestAiEm3>
            </Subtitle3>
            <DiscoverThe1 >
              {`We are bringing composability to Web3 by porting the best of Web2`}
                </DiscoverThe1>
            <Chart1  src={Chart1Image} alt={"chart 1"}/>
          </Frame1272>
        </Frame171>
      </Sec6>
      <Sec7 >
        <Frame1711 >
          <Frame1273 >
            <Subtitle4 >
              <ActionsIcon4  src={ActionsIcon4Image} alt={"Actions Icon"}/>
              <NeoFromQuestAiEm4 >
                {`JOIN US`}
                  </NeoFromQuestAiEm4>
            </Subtitle4>
            <DiscoverThe2 >
              {`We’re on Discord`}
                </DiscoverThe2>
            <Frame12512 >
              <Chart11 >
              </Chart11>
            </Frame12512>
            <LearnMore >
              <Link1 href="#" underline="hover"  >Connect with us</Link1>
              <About >
                {`on Discord and join a growing community of frontend Web3 enthusiasts.`}
                  </About>
            </LearnMore>
          </Frame1273>
        </Frame1711>
      </Sec7>
      {false &&
        <ReadyVid >
          <Frame1274 >
            <Frame12513 >
              <Subtitle5 >
                <ActionsIcon5  src={ActionsIcon5Image} alt={"Actions Icon"}/>
                <NeoFromQuestAiEm5 >
                  {`JOIN THE FUTURE`}
                    </NeoFromQuestAiEm5>
              </Subtitle5>
              <DiscoverThe3 >
                <DiscoverThe3Span1  >{`Ready for the `}</DiscoverThe3Span1>
                <DiscoverThe3Span2  >{`Future`}</DiscoverThe3Span2>
                <DiscoverThe3Span3  >{` of Frontend for Web3?`}</DiscoverThe3Span3>
              </DiscoverThe3>
              <Typeform >
              </Typeform>
            </Frame12513>
          </Frame1274>
        </ReadyVid>
      }
      <DiscoverSec >
        <Frame1275 >
          <Frame1262 >
            <Subtitle6 >
              <ActionsIcon6  src={ActionsIcon6Image} alt={"Actions Icon"}/>
              <NeoFromQuestAiEm6 >
                {`JOIN THE FUTURE`}
                  </NeoFromQuestAiEm6>
            </Subtitle6>
            <DiscoverThe4 >
              <DiscoverThe4Span1  >{`Join the `}</DiscoverThe4Span1>
              <DiscoverThe4Span2  >{`future`}</DiscoverThe4Span2>
              <DiscoverThe4Span3  >{` & build Web3 products at rapid speed`}</DiscoverThe4Span3>
            </DiscoverThe4>
            <ImportYourDifferen3 >
              {`The low-code movement is helping companies of all sizes remove redundant work. Quest enables you to build software products faster and go to market faster than ever.`}
                </ImportYourDifferen3>
            <LearnMore1 >
              <About1 >
                {`Check out our`}
                  </About1>
              <Link2 href="#" underline="hover"  >sample projects.</Link2>
            </LearnMore1>
            <ButtonOutlined1 variant="outlined" size="large" color="primary"    > Sign Up Now </ButtonOutlined1>
          </Frame1262>
        </Frame1275>
      </DiscoverSec>
      <BtmImage >
        <Sec4Image >
        </Sec4Image>
      </BtmImage>
    </ScreensDesktop>
  );
}

export default Web3;
