/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';

 
const MousePressed = styled("div")({  
  backgroundColor: `rgba(107, 104, 255, 1)`,  
  border: `1.5px solid rgba(138, 136, 255, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `0px 0px 2px 2px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `44px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
});
  
const RootB = styled("img")({  
  height: `12.35px`,  
  width: `6.1px`,  
  position: `absolute`,  
  left: `13px`,  
  top: `16px`,  
});
  
const RootW = styled("img")({  
  height: `12.35px`,  
  width: `6.1px`,  
  position: `absolute`,  
  left: `13px`,  
  top: `16px`,  
});
 
function RouteBtn3(props) {
  return (
    <MousePressed className={props.className} >
      {false &&
        <RootB  src={`assets/images/routebtn3_root_b.png`} alt={"root_b"}/>
      }
      <RootW  src={`assets/images/routebtn3_root_w.png`} alt={"root_w"}/>
    </MousePressed>
  );
}

export default RouteBtn3;
