/**********************************************************************
*
*   Types file generated by Quest
*
*   Types for the components props go in this file
*   To set up custom types for the components props, edit the corresponding types in this file
*   Once you edit a type to no longer by "any", be careful to not override it on your next export 
*   Verify diff before merging
*
*   For help and further details refer to: 
*   https://docs.quest.ai/react/fundamentals/exporting-code
*
*
**********************************************************************/

export interface RepoApiKeyProps {
  className?: any;
};

export interface Web3Props {
  className?: any;
};

export interface WorngLayoutTestProps {
  className?: any;
};

export interface Frame10Props {
  className?: any;
};

export interface Frame11Props {
  className?: any;
};

export interface Frame12Props {
  className?: any;
};

export interface Frame12Props {
  className?: any;
};

export interface Frame13Props {
  className?: any;
};

export interface Test123Props {
  className?: any;
};

export interface ImageUploadTestProps {
  className?: any;
};

export interface RouteBtn3Props {
  className?: any;
};

export interface Frame9Props {
  className?: any;
};

export interface TestcheckboxProps {
  className?: any;
};

